CREATE TABLE `sap_employee_basic_data`
(
            `ObjectID`                        varchar(80) DEFAULT NULL,
            `ETag`                            varchar(80) DEFAULT NULL,
            `EmployeeID`                      varchar(80) NOT NULL,
            `EmployeeUUID`                    varchar(80) DEFAULT NULL,
            `UserID`                          varchar(80) DEFAULT NULL,
            `IdentityUUID`                    varchar(80) DEFAULT NULL,
            `BusinessPartnerID`               varchar(80) DEFAULT NULL,
            `CurrentInternalEmployeeIndicator`varchar(80) DEFAULT NULL,
            `CurrentExternalEmployeeIndicator`varchar(80) DEFAULT NULL,
            `FormattedName`                   varchar(80) DEFAULT NULL,
            `TitleCode`                       varchar(80) DEFAULT NULL,
            `AcademicTitleCode`               varchar(80) DEFAULT NULL,
            `FirstName`                       varchar(80) DEFAULT NULL,
            `MiddleName`                      varchar(80) DEFAULT NULL,
            `LastName`                        varchar(80) DEFAULT NULL,
            `SecondLastName`                  varchar(80) DEFAULT NULL,
            `NickName`                        varchar(80) DEFAULT NULL,
            `GenderCode`                      varchar(80) DEFAULT NULL,
            `LanguageCode`                    varchar(80) DEFAULT NULL,
            `FormattedAddress`                varchar(80) DEFAULT NULL,
            `CountryCode`                     varchar(80) DEFAULT NULL,
            `RegionCode`                      varchar(80) DEFAULT NULL,
            `AddressLine1`                    varchar(80) DEFAULT NULL,
            `AddressLine2`                    varchar(80) DEFAULT NULL,
            `HouseNumber`                     varchar(80) DEFAULT NULL,
            `Street`                          varchar(80) DEFAULT NULL,
            `AddressLine4`                    varchar(80) DEFAULT NULL,
            `AddressLine5`                    varchar(80) DEFAULT NULL,
            `City`                            varchar(80) DEFAULT NULL,
            `PostalCode`                      varchar(80) DEFAULT NULL,
            `Phone`                           varchar(80) DEFAULT NULL,
            `Mobile`                          varchar(80) DEFAULT NULL,
            `Fax`                             varchar(80) DEFAULT NULL,
            `Email`                           varchar(80) DEFAULT NULL,
            `UserValidityStartDate`           varchar(80) DEFAULT NULL,
            `UserValidityEndDate`             varchar(80) DEFAULT NULL,
            `UserPasswordPolicyCode`          varchar(80) DEFAULT NULL,
            `UserLockedIndicator`             varchar(80) DEFAULT NULL,
            `TimeZoneCode`                    varchar(80) DEFAULT NULL,
            `ManagerUUID`                     varchar(80) DEFAULT NULL,
            `ManagerFormattedName`            varchar(80) DEFAULT NULL,
            `JobName`                         varchar(80) DEFAULT NULL,
            `CreatedOn`                       varchar(80) DEFAULT NULL,
            `CreatedBy`                       varchar(80) DEFAULT NULL,
            `ChangedOn`                       varchar(80) DEFAULT NULL,
            `ChangedBy`                       varchar(80) DEFAULT NULL,
            `EntityLastChangedOn`             varchar(80) DEFAULT NULL,
    PRIMARY KEY (`EmployeeID`)
) ENGINE = InnoDB
 DEFAULT CHARSET = utf8mb4;x